services:
  gear-go:
    container_name: gear-go
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["/gear-go", "serve"]
    network_mode: "host"

  subkey:
    image: docker.io/parity/subkey:latest
    command: ["inspect", "//Charlie"]
